export const networkLogos = [
  "google.png",
  "linkedin.png",
  "bcg.png",
  "nasa.png",
  "blackrock.png",
  "rtx.png",
  "kmw.png",

  "whoop.png",
  "pwc.png",
  "spacex.png",
  "salesforce.png",
  "perplexity.png",
  "verisk.png",

  "wellington.png",
  "sharkninja.png",
  "klaviyo.svg",
  "ms.webp",
  "keurig.png",
  "servicenow.png",
  "draftkings.svg",
  "wayfair.png",
  "chewy.png",
  "priceline.png",
  "harbourvest.png",
  "Scotiabank.png",
  "adobe.png",
  "bain.png",
  "xpo.svg",
  "tjx.png",
];
